### PR TITLE
Update BitBucket Client to use API 2.0

### LINKED ISSUE #1430: Can't install package from bitbucket repo
When adding the bitbucket repo of markupsafe to sublime text, sublime tries to download the package via the 1.0 api resulting in the following error:

Package Control: Error downloading repository. HTTP error 410 downloading https://api.bitbucket.org/1.0/repositories/teddy_beer_maniac/sublime-text-dependency-markupsafe/main-branch.
error: Package Control

### LINKED ISSUE #1435: The dependency `markupsafe` could not be installed or updated
Running into this issue again with Sublime Text 3207 (latest) and Package Control (latest) version.

Here is a debug log for the same,
```
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 74.207.232.232
  Resolved IPv6: ::ffff:74.207.232.232
Package Control: Found previously exported CA bundle at /Users/yuvraj/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (285226 bytes)
Package Control: Curl Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Trying to execute command /usr/local/opt/curl/bin/curl --connect-timeout 30 -sSL --tlsv1 --dump-header /var/folders/3d/5q_zvk7n4hq1pt9ps2nd8xcc0000gp/T/tmpftireo --user-agent 'Package Control v3.3.0' --header 'If-None-Match: "5d15bfa3-52e71"' --header 'If-Modified-Since: Fri, 28 Jun 2019 07:20:03 GMT' --header 'Accept-Encoding: bzip2,gzip,deflate' --cacert '/Users/yuvraj/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle' -v https://packagecontrol.io/channel_v3.json
Package Control: Curl HTTP Debug Write
    Trying 74.207.232.232:443...
  TCP_NODELAY set
  Connected to packagecontrol.io (74.207.232.232) port 443 (#0)
  ALPN, offering http/1.1
  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  Server certificate: packagecontrol.io
  Server certificate: RapidSSL RSA CA 2018
  Server certificate: DigiCert Global Root CA
Package Control: Curl HTTP Debug General
  GET /channel_v3.json HTTP/1.1
  Host: packagecontrol.io
  User-Agent: Package Control v3.3.0
  Accept: */*
  If-None-Match: "5d15bfa3-52e71"
  If-Modified-Since: Fri, 28 Jun 2019 07:20:03 GMT
  Accept-Encoding: bzip2,gzip,deflate
Package Control: Curl HTTP Debug Read
  Mark bundle as not supporting multiuse
Package Control: Curl HTTP Debug General
  HTTP/1.1 304 Not Modified
  Server: nginx
  Date: Fri, 28 Jun 2019 07:26:23 GMT
  Content-Type: application/json
  Last-Modified: Fri, 28 Jun 2019 07:20:03 GMT
  Connection: keep-alive
  ETag: "5d15bfa3-52e71"
  Content-Encoding: bzip2
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15552000
Package Control: Curl HTTP Debug General
  Connection #0 to host packagecontrol.io left intact
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/yuvraj/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
ignored packages updated to: ["Material Theme", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.0
Package Control: Download Debug
  URL: https://codeload.github.com/equinusocio/material-theme/zip/v4.1.5
  Timeout: 30
  Resolved IP: 140.82.114.10
  Resolved IPv6: ::ffff:140.82.114.10
Package Control: Found previously exported CA bundle at /Users/yuvraj/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (285226 bytes)
Package Control: Curl Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Trying to execute command /usr/local/opt/curl/bin/curl --connect-timeout 30 -sSL --tlsv1 --dump-header /var/folders/3d/5q_zvk7n4hq1pt9ps2nd8xcc0000gp/T/tmp6gjb2z --user-agent 'Package Control v3.3.0' --header 'Accept-Encoding: bzip2,gzip,deflate' --cacert '/Users/yuvraj/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle' -v https://codeload.github.com/equinusocio/material-theme/zip/v4.1.5
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/yuvraj/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
Package Control: Curl HTTP Debug Write
    Trying 140.82.114.10:443...
  TCP_NODELAY set
  Connected to codeload.github.com (140.82.114.10) port 443 (#0)
  ALPN, offering http/1.1
  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  Server certificate: *.github.com
  Server certificate: DigiCert SHA2 High Assurance Server CA
  Server certificate: DigiCert High Assurance EV Root CA
Package Control: Curl HTTP Debug General
  GET /equinusocio/material-theme/zip/v4.1.5 HTTP/1.1
  Host: codeload.github.com
  User-Agent: Package Control v3.3.0
  Accept: */*
  Accept-Encoding: bzip2,gzip,deflate
Package Control: Curl HTTP Debug Read
  Mark bundle as not supporting multiuse
Package Control: Curl HTTP Debug General
  HTTP/1.1 200 OK
  Date: Fri, 28 Jun 2019 07:26:32 GMT
  Content-Type: application/zip
  Content-Length: 3638769
  Access-Control-Allow-Origin: https://render.githubusercontent.com
  Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
  Strict-Transport-Security: max-age=31536000
  Vary: Authorization,Accept-Encoding
  X-Content-Type-Options: nosniff
  X-Frame-Options: deny
  X-XSS-Protection: 1; mode=block
  ETag: "0d34137f8cdc173d381f72bd04b3df29e9c0d455"
  Content-Disposition: attachment; filename=material-theme-4.1.5.zip
  X-Geo-Block-List: 
  Vary: Accept-Encoding
  X-GitHub-Request-Id: 6230:4A3B:FDEB:2BFD3:5D15C127
Package Control: Curl HTTP Debug General
  Connection #0 to host codeload.github.com left intact
Package Control: Skipping cache since the response is a zip file
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.0
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.0
Package Control: The dependency 'markupsafe' is not available
Package Control: The dependency 'markupsafe' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading /Users/yuvraj/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

Similar to this issue https://github.com/wbond/package_control/issues/1334

However, even after updating the package settings with 
```
"downloader_precedence":
	{
		"osx":
		[
			"curl",
                         "wget",
			"urllib"
		]
	},
```
and updating the curl version to 7.65.1, I am still getting the error. 

In short none of the fixes here are working for me.
This is happening for a variety of package including but not limited to GitGutter, MaterialTheme, SublimeLinter-Ruby etc.

### PR DESCRIPTION
**Pull request by deathaxe**
Fixes #1435 
Fixes #1430

This commit fixes the BitBucket client to use the REST API 2.0 as the prior used 1.0 is no longer available.

### CODE REVIEW

**Comment by basbloemsaat** [comment]
These are also marked missing in on the website. Can be fixed by changing the version as we only need the repository info:  e.g. https://api.bitbucket.org/1.0/repositories/StephaneBunel/pythonpep8autoformat should become https://api.bitbucket.org/2.0/repositories/StephaneBunel/pythonpep8autoformat.

**Comment by alecive** [comment]
I'd be more than happy to test this out [but I am yet to find any manual compilation instructions].. any help in this regard?

**Comment by 0xEEEE** [comment]
@deathaxe Thank you for your work.
I have modified the file _bitbucket_client.py_ with this commit, but still not working.
debug information as follows:

> Package Control: Installing 2 missing dependencies
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.1-beta2
Package Control: Download Debug
  URL: https://packagecontrol.io/channel_v3.json
  Timeout: 30
  Resolved IP: 50.116.34.243
  Resolved IPv6: 2600:3c02::f03c:91ff:fedf:6883
Package Control: Found previously exported CA bundle at /Users/*/Library/Application Support/Sublime Text 3/Packages/User/oscrypto-ca-bundle.crt (267421 bytes)
Package Control: Curl Debug Proxy
  http_proxy: 
  https_proxy: 
  proxy_username: 
  proxy_password: 
Package Control: Trying to execute command /usr/bin/curl --connect-timeout 30 -sSL --tlsv1 --dump-header /var/folders/86/gtjcd9596sn25h8bgskkxk7w0000gn/T/tmpf6s9me --user-agent 'Package Control v3.3.1-beta2' --header 'Accept-Encoding: bzip2,gzip,deflate' --header 'If-Modified-Since: Wed, 03 Jul 2019 02:50:03 GMT' --header 'If-None-Match: "5d1c17db-52d97"' --cacert '/Users/*/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle' -v https://packagecontrol.io/channel_v3.json
Package Control: Curl HTTP Debug Write
    Trying 50.116.34.243...
  TCP_NODELAY set
    Trying 2600:3c02::f03c:91ff:fedf:6883...
  TCP_NODELAY set
  Immediate connect fail for 2600:3c02::f03c:91ff:fedf:6883: No route to host
  Connected to packagecontrol.io (50.116.34.243) port 443 (#0)
  ALPN, offering h2
  ALPN, offering http/1.1
  Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
  successfully set certificate verify locations:
    CAfile: /Users/*/Library/Application Support/Sublime Text 3/Packages/User/Package Control.merged-ca-bundle
    CApath: none
  TLSv1.2 (OUT), TLS handshake, Client hello (1):
  TLSv1.2 (IN), TLS handshake, Server hello (2):
  TLSv1.2 (IN), TLS handshake, Certificate (11):
  TLSv1.2 (IN), TLS handshake, Server key exchange (12):
  TLSv1.2 (IN), TLS handshake, Server finished (14):
  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
  TLSv1.2 (OUT), TLS change cipher, Client hello (1):
  TLSv1.2 (OUT), TLS handshake, Finished (20):
  TLSv1.2 (IN), TLS change cipher, Client hello (1):
  TLSv1.2 (IN), TLS handshake, Finished (20):
  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
  ALPN, server accepted to use h2
  Server certificate:
   subject: CN=packagecontrol.io
   start date: May 29 00:00:00 2018 GMT
   expire date: Nov 27 12:00:00 2019 GMT
   subjectAltName: host "packagecontrol.io" matched cert's "packagecontrol.io"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=RapidSSL RSA CA 2018
   SSL certificate verify ok.
  Using HTTP2, server supports multi-use
  Connection state changed (HTTP/2 confirmed)
  Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
  Using Stream ID: 1 (easy handle 0x7fb2e180a400)
Package Control: Curl HTTP Debug General
  GET /channel_v3.json HTTP/2
  Host: packagecontrol.io
  User-Agent: Package Control v3.3.1-beta2
  Accept: */*
  Accept-Encoding: bzip2,gzip,deflate
  If-Modified-Since: Wed, 03 Jul 2019 02:50:03 GMT
  If-None-Match: "5d1c17db-52d97"
Package Control: Curl HTTP Debug Read
  Connection state changed (MAX_CONCURRENT_STREAMS updated)!
Package Control: Curl HTTP Debug General
  HTTP/2 304 
  server: nginx
  date: Wed, 03 Jul 2019 02:57:39 GMT
  content-type: application/json
  last-modified: Wed, 03 Jul 2019 02:50:03 GMT
  etag: "5d1c17db-52d97"
  content-encoding: bzip2
  vary: Accept-Encoding
  strict-transport-security: max-age=15552000
Package Control: Curl HTTP Debug General
  Connection #0 to host packagecontrol.io left intact
Package Control: Using cached content for https://packagecontrol.io/channel_v3.json from /Users/*/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: The dependency 'markupsafe' is not available
Package Control: Fetching list of available packages and dependencies
  Platform: osx-x64
  Sublime Text Version: 3207
  Package Control Version: 3.3.1-beta2
Package Control: The dependency 'python-jinja2' is not available
Package Control: Skipping automatic upgrade, last run at 2019-07-03 10:20:46, next run at 2019-07-03 11:20:46 or after

And when i manually install it show:
> Package Control: The dependency 'markupsafe' is installed, but there are no available releases; leaving alone
Package Control: The dependency 'python-jinja2' is installed, but there are no available releases; leaving alone

How can i fix it?

**Comment by FichteFoll** [comment]
Because the crawler uses the same code as PC to retrieve packages (and dependencies), the pre-cached channel does not contain these dependencies as their download fails. https://packagecontrol.io/channel_v3.json

**Comment by 0xEEEE** [comment]
> Because the crawler uses the same code as PC to retrieve packages (and dependencies), the pre-cached channel does not contain these dependencies as their download fails. https://packagecontrol.io/channel_v3.json

Thank you.
I edited the JSON file and uploaded 'python-jinja2' 'markupsafe' to GitHub to create the source.
[https://github.com/0xEEEE/dependencies_st](url)
It seems to be working now.

**Comment by niosus** [comment]
This seems to stop lots of packages from installing. Are there any plans on merging this? Can I help somehow?

**Comment by wbond** [comment]
Yes, I am planning on working on getting some things merged into Package Control in the next couple of weeks and cutting a new release.

You can help by merging this into your own repo and running the code locally on your machine to see if there are any bugs.

**Comment by niosus** [comment]
Sure, on it. Any specific command that would be particularly interesting to test?

**Comment by wbond** [comment]
I would add a "Repository" that is the URL of a bitbucket repo containing a plugin, and then go through the process of installing it. That will cause it to hit the API to get info, and then determine the download URL and use it to fetch the zip file.

**Comment by daniele-niero** [comment]
Is this the reason my package isn't available anymore? 
From the PackageControl web page I see a "MISSING" message with a yellow icon, just below my package name.  (https://packagecontrol.io/packages/Environment%20Settings)

**Comment by FichteFoll** [comment]
Yes, packages from bitbucket cannot be crawled by the crawler currently and end up as missing in the package list.

**Comment by joshua-golub** [comment]
On July 9, @wbond said "Yes, I am planning on working on getting some things merged into Package Control in the next couple of weeks and cutting a new release."

Is there any update on this? Our plugin (hosted in Bitbucket) remains broken until it is fixed.

**Comment by wbond** [comment]
I would recommend pushing it up to GitHub in the time being. It will require merging, testing, test deployment (to users that have opted into prereleases) and then final deployment. Based on how my past month has gone, I doubt this will likely be done before 2-4 weeks, at the least.

**Comment by joshua-golub** [comment]
Well, I didn't implement the change in question, so the original author will need to do that...

**Comment by joshua-golub** [comment]
When will this merge be picked up by the crawler? I am still seeing this message for [my package](https://packagecontrol.io/packages/Format%20JSDoc%20%40params):

> Package info was unavailable last time crawler ran. Error downloading repository. HTTP error 410 downloading https://api.bitbucket.org/1.0/repositories/finitewisdom/sublime-jsdocparam/main-branch.

**Comment by wbond** [comment]
I haven't updated packagecontrol.io with this patch yet since I need to do some testing, but I have to get the local testing environment up and running to make sure the recent changes don't break the server.

**Comment by joshua-golub** [comment]
Are you getting any closer to updating packagecontrol.io? Just curious. My package has been offline for many months now.

**Pull request merged**
