### PR TITLE
fix: GitLab Repository Provider missing from the respository_provider.py

### PR DESCRIPTION
**Pull request by TheSecEng**
This should fix the gitlab repository provider implementation by implementing the GitLabClient into the actual repository_providers functions.

### CODE REVIEW

**Comment by deathaxe** [comment]
This is already fixed in four-point-oh

**Comment by TheSecEng** [comment]
@deathaxe Yes, I mentioned that inside of the `package_control_channel` however @wbond had requested an issue be created so that this can be resolved now while the `four-point-oh` branch is being finished.

**Comment by deathaxe** [comment]
Oh, finally PC3 receives updates again?

**Comment by wbond** [comment]
Thanks for this!

**Pull request merged**
