### PR TITLE
Gitlab Client and Provider Support

### LINKED ISSUE #719: support gitlab
Is it possible to host packages on [gitlab.com](https://gitlab.com/users/sign_in)'s git hosting service ([demo repository here](https://gitlab.com/fnkr/gitignore))?

### PR DESCRIPTION
**Pull request by TheSecEng**
## What

Gitlab implementation for Client, User Provider and Repositories.

- [x] Unit Testing
- [x] Real Gitlab Test

fixes #719

### CODE REVIEW

**Comment by wbond** [comment]
I just pushed a couple of commits related to formatting. Some of the changes reverted some formatting changes so the diffs don't contain unreleased changes. Some of the change just tweak formatting/indentation to match the rest of the project. Hope you don't mind!

**Comment by TheSecEng** [comment]
Nope, not at all. I need to test this further as I attempted to use it this morning using `https://gitlab.com/packagecontrol-test` as the test and it's having issues parsing JSON. So their must be some more bugs to squash

**Comment by wbond** [comment]
I did a cursory look over it, and nothing jumped out, so my next steps will be to try using it. 😄

**Comment by TheSecEng** [comment]
> I did a cursory look over it, and nothing jumped out, so my next steps will be to try using it. 😄

Awesome, well it is working. I forgot to run a local version on my system that had Gitlab + oscrypto updated (on Big Sur)

**Comment by wbond** [comment]
I fixed a bug I ran into when trying to install livesession and preemptively fixed hard-coded references to the `master` branch. I'm going to merge this in, and hopefully we can get some users testing it.

**Comment by wbond** [comment]
Thanks for your work on this!

**Comment by hxss** [comment]
when will we be able to use this feature?

**Comment by wbond** [comment]
I should hopefully be doing a beta release with this in the next few days.

**Comment by TheSecEng** [comment]
> when will we be able to use this feature?

@hxss do you have any packages currently hosted on gitlab? I am interested in seeing how many people will now utilize this.

**Comment by hxss** [comment]
@TheSecEng yes, I just copied all my packages to gitlab. I hope in the future I can give up my bitbucket

**Pull request merged**
